version: "3.7"

services:
  # This service runs the source database
  source_postgresql:
    image: postgres:13
    container_name: source_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: source_postgres
      POSTGRES_PASSWORD: source_postgres
      POSTGRES_DB: source_postgres

  # This service runs the target database
  target_postgres:
    image: postgres:13
    container_name: target_db
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: target_postgres
      POSTGRES_PASSWORD: target_postgres
      POSTGRES_DB: target_postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
